/*
 * Simple API overview
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OKResponse string

// List of OKResponse
const (
	OK OkResponse = "OK"
)
